export default [
  {
    id: "formId",
    label: "ID",
    type: "text",
    stateKey: "id",
    readOnly: true,
  },
  {
    id: "formName",
    label: "Name",
    type: "text",
    stateKey: "name",
    readOnly: false,
  },
  {
    id: "formDescription",
    label: "Description",
    type: "textarea",
    stateKey: "description",
    readOnly: false,
  },
  {
    id: "formIsString",
    label: "Is String",
    type: "checkbox",
    stateKey: "isString",
    readOnly: false,
  },
  {
    id: "formStringValue",
    label: "String Value",
    type: "text",
    stateKey: "stringValue",
    readOnly: false,
  },
  {
    id: "formIsBool",
    label: "Is Bool",
    type: "checkbox",
    stateKey: "isBool",
    readOnly: false,
  },
  {
    id: "formBoolValue",
    label: "Bool Value",
    type: "checkbox",
    stateKey: "boolValue",
    readOnly: false,
  },
  {
    id: "formIsInt",
    label: "Is Int",
    type: "checkbox",
    stateKey: "isInt",
    readOnly: false,
  },
  {
    id: "formIntVal",
    label: "Int Value",
    type: "number",
    stateKey: "intVal",
    readOnly: false,
  },
];
