export default [
  {
    id: "formId",
    label: "ID",
    type: "label",
    stateKey: "ID",
    readOnly: true,
  },
  {
    id: "formName",
    label: "Name",
    type: "text",
    stateKey: "Name",
    readOnly: false,
  },
  {
    id: "formDescription",
    label: "Description",
    type: "textarea",
    stateKey: "Description",
    readOnly: false,
  },
  {
    id: "formIsString",
    label: "Is String",
    type: "checkbox",
    stateKey: "IsString",
    readOnly: false,
  },
  {
    id: "formStringValue",
    label: "String Value",
    type: "text",
    stateKey: "StringValue",
    readOnly: false,
  },
  {
    id: "formIsBool",
    label: "Is Bool",
    type: "checkbox",
    stateKey: "IsBool",
    readOnly: false,
  },
  {
    id: "formBoolValue",
    label: "Bool Value",
    type: "checkbox",
    stateKey: "BoolValue",
    readOnly: false,
  },
  {
    id: "formIsInt",
    label: "Is Int",
    type: "checkbox",
    stateKey: "IsInt",
    readOnly: false,
  },
  {
    id: "formIntVal",
    label: "Int Value",
    type: "number",
    stateKey: "IntValue",
    readOnly: false,
  },
];
